<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "stagedeal"
 *
 * Auto generated by Extension Builder 2013-04-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Advanced Exeption',
	'description' => 'Advanced Exception Handling',
	'category' => 'plugin',
	'author' => 'Eric Depta',
	'author_email' => 'info@ericdepta.de',
	'author_company' => 'Kommunikations-Design Eric Depta',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0-6.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
